### ISSUE TITLE
New budget_allocation

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/budgeting#103]
* budget_allocation :: แจกแจงเงินจากมุมมองต่างๆ ส่งต่อให้ budget_plan เบื้องต้นมีแค่ analytic_account_id
  * budget.allocation.line
    * analytic_account_id -> Main
    * description
    * amount
* budget_allocation_dimension (adding dynamic dimensions) :: ทำหน้าที่เพิ่ม dynamic dimension
  * depends = "budget_allocation"
  * budget.allocation.line
    * xxx_id
    * yyy_id
    * zzz_id
* budget_allocation_program :: เพิ่ม custom field program
  * depends = "budget_allocation"
  * budget.allocation.line
    * program_id (res.program)
* budget_allocation_fund :: เพิ่ม custom field fund
  * depends = "budget_allocation"
  * budget.allocation.line
    * fund_id (res.fund)

ส่วนของการเช็ค Budget Constraints (เช่น Project / Year / Activity สามารถใช้เงิน ใน PR / PO ได้เป็นกี่ % ของยอด  Amount ที่วางไว้) สามารถใช้ Server Action ได้ หรือถ้าให้คนใช้งานง่ายหน่อยก็สามารถมี UI ที่ดูเกี่ยวข้องกับ Budgeting ได้เช่น

* budget_constraints :: เป็น new model ที่เก็บ สูตรการคำนวณ (eval) โดยสามารถเพิ่มได้ไม่จำกัด
  * depends = "budget_control"

**Comment by kittiu** [comment]
@Saran440 @ps-tubtim

**Comment by Saran440** [comment]
budget_allocation > Done https://github.com/ecosoft-odoo/budgeting/tree/14.0/budget_allocation
budget_allocation_dimension > Done https://github.com/ecosoft-odoo/budgeting/tree/14.0/budget_allocation_dimension
budget_allocation_program > ไม่จำเป็นต้องมีแล้ว สามารถใช้ Dimension แทนได้
budget_allocation_fund > Done https://github.com/ecosoft-odoo/budgeting/tree/14.0/budget_allocation_fund
budget_allocation_fund สามารถใช้ budget_allocation_dimension แทนได้ แต่หน้าจออาจทำให้ User ดูยากหน่อย เลยยังทำเก็บไว้ เผื่อจะเปลี่ยนเป็นแบบ Dimension แทน


budget_constraints > ยังไม่ได้ทำ

**Comment by kittiu** [comment]
**budget_constraint**

* budget.period
  * use_budget_constraint = True / False

if use budget constraint, then after check_budget(), then call, check_budget_constraint(). You can see how check_budget() is returning.

And check_budget_constraint() will call call each budget.constraint in sequence. I.e., we may have 3 constraint to check.

* New model = budget.constraint
  * sequence
  * name
  * description
  * server_action_id

Then, in server action, we can write any thing that return False (pass test), or return list of error message, i.e., ["xxx", "yyy"]

**Comment by kittiu** [comment]
@Saran440 please close if done.

**Comment by Saran440** [comment]
Done

budget_constraints > https://github.com/ecosoft-odoo/budgeting/tree/14.0/budget_constraint
