### ISSUE TITLE
As new user, I log in and get into budgeting menu, and I got this error.

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/budgeting#5]
To me, the security designed properly.

* Why I can see the menu, but can't click in.
* If I am not a manager, I can't access period?

![Selection_030](https://user-images.githubusercontent.com/1973598/108158711-19be7c80-7118-11eb-97f6-5fdd9bfd43d3.png)

**Comment by kittiu** [comment]
@Saran440

**Comment by Saran440** [comment]
You used Budget Management instead of Budget User.
Budget User is not ready access rights.
